// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using Tarteeb.XChanger.Entities.Data;

#nullable disable

namespace Tarteeb.XChanger.Migrations;

[DbContext(typeof(XChangerDbContext))]
partial class XChangerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

        modelBuilder.Entity("Tarteeb.XChanger.Models.ExternalApplicantModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .HasColumnType("TEXT");

                b.Property<Guid>("GroupId")
                    .HasColumnType("TEXT");

                b.Property<string>("GroupName")
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .HasColumnType("TEXT");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("ExternalApplicants");
            });
#pragma warning restore 612, 618
    }
}
